version: '3'
services:
  forward:
    build:
      context: .
    container_name: gcloud-forward
    image: gcloud-forward
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/usr/src/app/sa-key.json
      - /home/jderuere/.config/gcloud:/config/gcloud
    command: ['project', 'id', 'svc-name', 'port', 'namespace']
    ports:
      - 8000:8000
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/sa-key.json
      - CLOUDSDK_CONFIG=/config/gcloud
    networks:
      - cloud
networks:
  cloud:
    external: true